language: java
jdk:
  - openjdk6
script: "mvn deploy --settings .travis-settings.xml"
env:
  global:
    - secure: |-
        o8+uoQTHy3rh6rKPHeU78AW3vQJbfnBmc1mhUMJJ1hUYyYbRFpN0EQge7JP9jL1CFOtsQyG
        SdXfx37SFw7WWpbYW2eCPWC5vuQziFcAuUlGd45YKOsBsORfpr6xMVnLNIUs/qEsC//uRqo
        mZ3UUuVoW0it1xpA/0HuBKczNPiUo=

    - secure: |-
        ADfGhzMjpiAtgXJfEu6/g5utExDtjxCXGDnKPvJ2kKnjyjMmkJgw9h4KB0RuO0nAHRe4OV7
        omk8MnYdX27HHgj4fiTzfGQVCc2R/OYyJXl2OOS9zmt/FAq9nz3c2uhV6LA+fQhENubhaul
        oJ4tjTND1dLsLAjIcanL6dFz5W80s=
