# Ok, so, oddly enough, I have to specify language: objective-c for my build to be triggered in an OSX env
# os: osx
# language: java
language: objective-c
jdk:
  - openjdk6
script: "mvn deploy --settings .travis-settings.xml"
env:
  global:
    - secure: |-
        l15P0O3LSHUemqpFvLNr/xWPZR7+2G3rpDBw1A5xmZpvKFw1SGlxP32hHkjDXZIioGJ0h1s
        GXtQo03Uf1AIBOqiq4yIllnwIS6GsFX4HonFWCktHltX6ZuRICMaAbRdHd4cI3KYH3O0qpF
        vbrXZ49ayVIsnPlFiep7/MvFOb+YQ=

    - secure: |-
        hESe389/pqjPIWDR1qz0K7YvjeEN2m+G3HlfG+WFym9F1v0vyP5tTlwKENqwlkV5JJy3cRk
        VQb/HDBbfuwZ9QqVvHZJ2MMhTkCNMVV60SVKAxMUMxO7UPbStyk+BVIkVHjpVD9+bnBa/gZ
        u/WF9vzb+YYq8poyZndlIxxOaS16A=
