# Ok, so, oddly enough, I have to specify language: objective-c for my build to be triggered in an OSX env
# os: osx
# language: java
language: objective-c
jdk:
  - openjdk6
script:
  - echo "Installed JRE/JDKs:"
  - /usr/libexec/java_home -V
  - echo ""
  - export JAVA_HOME=$(/usr/libexec/java_home -v 1.6)
  - echo "Now set to:"
  - java -version
  - mvn -B -V deploy --settings .travis-settings.xml
env:
  global:
    - secure: "Lge5UCp/yESW4pM+wTjIvIKA2+RMH3LeQYCHdUgzvUVojmQ8deJS2JLZ4EdORqT+sMolQCUFuRsneib5OJYA3nxFdrMSLRCnRM0sxI20TJ2KDUuslhIUnB/bXU8saNgF22POjp0wJGOd7fSY09+/z3hnDT/wmey859WFAOJUUuI="
    - secure: "erqbGY3AkJ6qdrPbRtnxJfvTDL77erH3q/idx3s1dHJDuYQBv7nirG1uNSu1exiyBHMUse8MU5OGcIaHoWp5cTNIoH9DD6fKNEhdlgTvqcMOlx4oW/Mc8xO7OU4CjyEKgNAvQjK6bjyz72jX19R22foSTAlns5pHpQtsYfPUowM="
